//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeItAirLines.CrossCutting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CodeItAirLines.CrossCutting.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PassengerCanNotDrive {
            get {
                return ResourceManager.GetString("PassengerCanNotDrive", resourceCulture);
            }
        }
        
        public static string DriverIsRequired {
            get {
                return ResourceManager.GetString("DriverIsRequired", resourceCulture);
            }
        }
        
        public static string StewardessesNotAloneWithPilot {
            get {
                return ResourceManager.GetString("StewardessesNotAloneWithPilot", resourceCulture);
            }
        }
        
        public static string FlightOfficersNotAloneWithCabinChief {
            get {
                return ResourceManager.GetString("FlightOfficersNotAloneWithCabinChief", resourceCulture);
            }
        }
        
        public static string PrisonerNotAloneWithPassengers {
            get {
                return ResourceManager.GetString("PrisonerNotAloneWithPassengers", resourceCulture);
            }
        }
        
        public static string InvalidResponse {
            get {
                return ResourceManager.GetString("InvalidResponse", resourceCulture);
            }
        }
    }
}
