//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeItAirLines.CrossCutting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CodeItAirLines.CrossCutting.Resources.SystemMessages", typeof(SystemMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SelectTheDriver {
            get {
                return ResourceManager.GetString("SelectTheDriver", resourceCulture);
            }
        }
        
        public static string SelectThePassenger {
            get {
                return ResourceManager.GetString("SelectThePassenger", resourceCulture);
            }
        }
        
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        public static string Airplane {
            get {
                return ResourceManager.GetString("Airplane", resourceCulture);
            }
        }
        
        public static string DepartureGate {
            get {
                return ResourceManager.GetString("DepartureGate", resourceCulture);
            }
        }
        
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        public static string Pilot {
            get {
                return ResourceManager.GetString("Pilot", resourceCulture);
            }
        }
        
        public static string CabinChief {
            get {
                return ResourceManager.GetString("CabinChief", resourceCulture);
            }
        }
        
        public static string FlightOfficer {
            get {
                return ResourceManager.GetString("FlightOfficer", resourceCulture);
            }
        }
        
        public static string Stewardess {
            get {
                return ResourceManager.GetString("Stewardess", resourceCulture);
            }
        }
        
        public static string PoliceOfficer {
            get {
                return ResourceManager.GetString("PoliceOfficer", resourceCulture);
            }
        }
        
        public static string Prisoner {
            get {
                return ResourceManager.GetString("Prisoner", resourceCulture);
            }
        }
        
        public static string PressKey {
            get {
                return ResourceManager.GetString("PressKey", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string ProblemenDescription {
            get {
                return ResourceManager.GetString("ProblemenDescription", resourceCulture);
            }
        }
    }
}
